module.exports = {
        typeDefs: // Code generated by Prisma (prisma@1.34.0). DO NOT EDIT.
  // Please don't change this file manually but run `prisma generate` to update it.
  // For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

/* GraphQL */ `type AggregateBalance {
  count: Int!
}

type AggregateFinance {
  count: Int!
}

type AggregateQueryOrder {
  count: Int!
}

type AggregateUser {
  count: Int!
}

type AggregateWebAddBalance {
  count: Int!
}

type AggregateWebAmountDiscount {
  count: Int!
}

type Balance {
  id: ID!
  Balance: String
  DiscountCM: String
  DiscountCT: String
  DiscountCU: String
}

type BalanceConnection {
  pageInfo: PageInfo!
  edges: [BalanceEdge]!
  aggregate: AggregateBalance!
}

input BalanceCreateInput {
  id: ID
  Balance: String
  DiscountCM: String
  DiscountCT: String
  DiscountCU: String
}

type BalanceEdge {
  node: Balance!
  cursor: String!
}

enum BalanceOrderByInput {
  id_ASC
  id_DESC
  Balance_ASC
  Balance_DESC
  DiscountCM_ASC
  DiscountCM_DESC
  DiscountCT_ASC
  DiscountCT_DESC
  DiscountCU_ASC
  DiscountCU_DESC
}

type BalancePreviousValues {
  id: ID!
  Balance: String
  DiscountCM: String
  DiscountCT: String
  DiscountCU: String
}

type BalanceSubscriptionPayload {
  mutation: MutationType!
  node: Balance
  updatedFields: [String!]
  previousValues: BalancePreviousValues
}

input BalanceSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: BalanceWhereInput
  AND: [BalanceSubscriptionWhereInput!]
  OR: [BalanceSubscriptionWhereInput!]
  NOT: [BalanceSubscriptionWhereInput!]
}

input BalanceUpdateInput {
  Balance: String
  DiscountCM: String
  DiscountCT: String
  DiscountCU: String
}

input BalanceUpdateManyMutationInput {
  Balance: String
  DiscountCM: String
  DiscountCT: String
  DiscountCU: String
}

input BalanceWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  Balance: String
  Balance_not: String
  Balance_in: [String!]
  Balance_not_in: [String!]
  Balance_lt: String
  Balance_lte: String
  Balance_gt: String
  Balance_gte: String
  Balance_contains: String
  Balance_not_contains: String
  Balance_starts_with: String
  Balance_not_starts_with: String
  Balance_ends_with: String
  Balance_not_ends_with: String
  DiscountCM: String
  DiscountCM_not: String
  DiscountCM_in: [String!]
  DiscountCM_not_in: [String!]
  DiscountCM_lt: String
  DiscountCM_lte: String
  DiscountCM_gt: String
  DiscountCM_gte: String
  DiscountCM_contains: String
  DiscountCM_not_contains: String
  DiscountCM_starts_with: String
  DiscountCM_not_starts_with: String
  DiscountCM_ends_with: String
  DiscountCM_not_ends_with: String
  DiscountCT: String
  DiscountCT_not: String
  DiscountCT_in: [String!]
  DiscountCT_not_in: [String!]
  DiscountCT_lt: String
  DiscountCT_lte: String
  DiscountCT_gt: String
  DiscountCT_gte: String
  DiscountCT_contains: String
  DiscountCT_not_contains: String
  DiscountCT_starts_with: String
  DiscountCT_not_starts_with: String
  DiscountCT_ends_with: String
  DiscountCT_not_ends_with: String
  DiscountCU: String
  DiscountCU_not: String
  DiscountCU_in: [String!]
  DiscountCU_not_in: [String!]
  DiscountCU_lt: String
  DiscountCU_lte: String
  DiscountCU_gt: String
  DiscountCU_gte: String
  DiscountCU_contains: String
  DiscountCU_not_contains: String
  DiscountCU_starts_with: String
  DiscountCU_not_starts_with: String
  DiscountCU_ends_with: String
  DiscountCU_not_ends_with: String
  AND: [BalanceWhereInput!]
  OR: [BalanceWhereInput!]
  NOT: [BalanceWhereInput!]
}

input BalanceWhereUniqueInput {
  id: ID
}

type BatchPayload {
  count: Long!
}

scalar DateTime

type Finance {
  id: ID!
  Orderid: String
  Account: String
  Amount: String
  BalanceBefore: String
  BalanceAfter: String
  Cost: String
  Name: String
  Price: String
  Time: DateTime
}

type FinanceConnection {
  pageInfo: PageInfo!
  edges: [FinanceEdge]!
  aggregate: AggregateFinance!
}

input FinanceCreateInput {
  id: ID
  Orderid: String
  Account: String
  Amount: String
  BalanceBefore: String
  BalanceAfter: String
  Cost: String
  Name: String
  Price: String
  Time: DateTime
}

type FinanceEdge {
  node: Finance!
  cursor: String!
}

enum FinanceOrderByInput {
  id_ASC
  id_DESC
  Orderid_ASC
  Orderid_DESC
  Account_ASC
  Account_DESC
  Amount_ASC
  Amount_DESC
  BalanceBefore_ASC
  BalanceBefore_DESC
  BalanceAfter_ASC
  BalanceAfter_DESC
  Cost_ASC
  Cost_DESC
  Name_ASC
  Name_DESC
  Price_ASC
  Price_DESC
  Time_ASC
  Time_DESC
}

type FinancePreviousValues {
  id: ID!
  Orderid: String
  Account: String
  Amount: String
  BalanceBefore: String
  BalanceAfter: String
  Cost: String
  Name: String
  Price: String
  Time: DateTime
}

type FinanceSubscriptionPayload {
  mutation: MutationType!
  node: Finance
  updatedFields: [String!]
  previousValues: FinancePreviousValues
}

input FinanceSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: FinanceWhereInput
  AND: [FinanceSubscriptionWhereInput!]
  OR: [FinanceSubscriptionWhereInput!]
  NOT: [FinanceSubscriptionWhereInput!]
}

input FinanceUpdateInput {
  Orderid: String
  Account: String
  Amount: String
  BalanceBefore: String
  BalanceAfter: String
  Cost: String
  Name: String
  Price: String
  Time: DateTime
}

input FinanceUpdateManyMutationInput {
  Orderid: String
  Account: String
  Amount: String
  BalanceBefore: String
  BalanceAfter: String
  Cost: String
  Name: String
  Price: String
  Time: DateTime
}

input FinanceWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  Orderid: String
  Orderid_not: String
  Orderid_in: [String!]
  Orderid_not_in: [String!]
  Orderid_lt: String
  Orderid_lte: String
  Orderid_gt: String
  Orderid_gte: String
  Orderid_contains: String
  Orderid_not_contains: String
  Orderid_starts_with: String
  Orderid_not_starts_with: String
  Orderid_ends_with: String
  Orderid_not_ends_with: String
  Account: String
  Account_not: String
  Account_in: [String!]
  Account_not_in: [String!]
  Account_lt: String
  Account_lte: String
  Account_gt: String
  Account_gte: String
  Account_contains: String
  Account_not_contains: String
  Account_starts_with: String
  Account_not_starts_with: String
  Account_ends_with: String
  Account_not_ends_with: String
  Amount: String
  Amount_not: String
  Amount_in: [String!]
  Amount_not_in: [String!]
  Amount_lt: String
  Amount_lte: String
  Amount_gt: String
  Amount_gte: String
  Amount_contains: String
  Amount_not_contains: String
  Amount_starts_with: String
  Amount_not_starts_with: String
  Amount_ends_with: String
  Amount_not_ends_with: String
  BalanceBefore: String
  BalanceBefore_not: String
  BalanceBefore_in: [String!]
  BalanceBefore_not_in: [String!]
  BalanceBefore_lt: String
  BalanceBefore_lte: String
  BalanceBefore_gt: String
  BalanceBefore_gte: String
  BalanceBefore_contains: String
  BalanceBefore_not_contains: String
  BalanceBefore_starts_with: String
  BalanceBefore_not_starts_with: String
  BalanceBefore_ends_with: String
  BalanceBefore_not_ends_with: String
  BalanceAfter: String
  BalanceAfter_not: String
  BalanceAfter_in: [String!]
  BalanceAfter_not_in: [String!]
  BalanceAfter_lt: String
  BalanceAfter_lte: String
  BalanceAfter_gt: String
  BalanceAfter_gte: String
  BalanceAfter_contains: String
  BalanceAfter_not_contains: String
  BalanceAfter_starts_with: String
  BalanceAfter_not_starts_with: String
  BalanceAfter_ends_with: String
  BalanceAfter_not_ends_with: String
  Cost: String
  Cost_not: String
  Cost_in: [String!]
  Cost_not_in: [String!]
  Cost_lt: String
  Cost_lte: String
  Cost_gt: String
  Cost_gte: String
  Cost_contains: String
  Cost_not_contains: String
  Cost_starts_with: String
  Cost_not_starts_with: String
  Cost_ends_with: String
  Cost_not_ends_with: String
  Name: String
  Name_not: String
  Name_in: [String!]
  Name_not_in: [String!]
  Name_lt: String
  Name_lte: String
  Name_gt: String
  Name_gte: String
  Name_contains: String
  Name_not_contains: String
  Name_starts_with: String
  Name_not_starts_with: String
  Name_ends_with: String
  Name_not_ends_with: String
  Price: String
  Price_not: String
  Price_in: [String!]
  Price_not_in: [String!]
  Price_lt: String
  Price_lte: String
  Price_gt: String
  Price_gte: String
  Price_contains: String
  Price_not_contains: String
  Price_starts_with: String
  Price_not_starts_with: String
  Price_ends_with: String
  Price_not_ends_with: String
  Time: DateTime
  Time_not: DateTime
  Time_in: [DateTime!]
  Time_not_in: [DateTime!]
  Time_lt: DateTime
  Time_lte: DateTime
  Time_gt: DateTime
  Time_gte: DateTime
  AND: [FinanceWhereInput!]
  OR: [FinanceWhereInput!]
  NOT: [FinanceWhereInput!]
}

input FinanceWhereUniqueInput {
  id: ID
}

scalar Long

type Mutation {
  createBalance(data: BalanceCreateInput!): Balance!
  updateBalance(data: BalanceUpdateInput!, where: BalanceWhereUniqueInput!): Balance
  updateManyBalances(data: BalanceUpdateManyMutationInput!, where: BalanceWhereInput): BatchPayload!
  upsertBalance(where: BalanceWhereUniqueInput!, create: BalanceCreateInput!, update: BalanceUpdateInput!): Balance!
  deleteBalance(where: BalanceWhereUniqueInput!): Balance
  deleteManyBalances(where: BalanceWhereInput): BatchPayload!
  createFinance(data: FinanceCreateInput!): Finance!
  updateFinance(data: FinanceUpdateInput!, where: FinanceWhereUniqueInput!): Finance
  updateManyFinances(data: FinanceUpdateManyMutationInput!, where: FinanceWhereInput): BatchPayload!
  upsertFinance(where: FinanceWhereUniqueInput!, create: FinanceCreateInput!, update: FinanceUpdateInput!): Finance!
  deleteFinance(where: FinanceWhereUniqueInput!): Finance
  deleteManyFinances(where: FinanceWhereInput): BatchPayload!
  createQueryOrder(data: QueryOrderCreateInput!): QueryOrder!
  updateQueryOrder(data: QueryOrderUpdateInput!, where: QueryOrderWhereUniqueInput!): QueryOrder
  updateManyQueryOrders(data: QueryOrderUpdateManyMutationInput!, where: QueryOrderWhereInput): BatchPayload!
  upsertQueryOrder(where: QueryOrderWhereUniqueInput!, create: QueryOrderCreateInput!, update: QueryOrderUpdateInput!): QueryOrder!
  deleteQueryOrder(where: QueryOrderWhereUniqueInput!): QueryOrder
  deleteManyQueryOrders(where: QueryOrderWhereInput): BatchPayload!
  createUser(data: UserCreateInput!): User!
  updateUser(data: UserUpdateInput!, where: UserWhereUniqueInput!): User
  updateManyUsers(data: UserUpdateManyMutationInput!, where: UserWhereInput): BatchPayload!
  upsertUser(where: UserWhereUniqueInput!, create: UserCreateInput!, update: UserUpdateInput!): User!
  deleteUser(where: UserWhereUniqueInput!): User
  deleteManyUsers(where: UserWhereInput): BatchPayload!
  createWebAddBalance(data: WebAddBalanceCreateInput!): WebAddBalance!
  updateWebAddBalance(data: WebAddBalanceUpdateInput!, where: WebAddBalanceWhereUniqueInput!): WebAddBalance
  updateManyWebAddBalances(data: WebAddBalanceUpdateManyMutationInput!, where: WebAddBalanceWhereInput): BatchPayload!
  upsertWebAddBalance(where: WebAddBalanceWhereUniqueInput!, create: WebAddBalanceCreateInput!, update: WebAddBalanceUpdateInput!): WebAddBalance!
  deleteWebAddBalance(where: WebAddBalanceWhereUniqueInput!): WebAddBalance
  deleteManyWebAddBalances(where: WebAddBalanceWhereInput): BatchPayload!
  createWebAmountDiscount(data: WebAmountDiscountCreateInput!): WebAmountDiscount!
  updateWebAmountDiscount(data: WebAmountDiscountUpdateInput!, where: WebAmountDiscountWhereUniqueInput!): WebAmountDiscount
  updateManyWebAmountDiscounts(data: WebAmountDiscountUpdateManyMutationInput!, where: WebAmountDiscountWhereInput): BatchPayload!
  upsertWebAmountDiscount(where: WebAmountDiscountWhereUniqueInput!, create: WebAmountDiscountCreateInput!, update: WebAmountDiscountUpdateInput!): WebAmountDiscount!
  deleteWebAmountDiscount(where: WebAmountDiscountWhereUniqueInput!): WebAmountDiscount
  deleteManyWebAmountDiscounts(where: WebAmountDiscountWhereInput): BatchPayload!
}

enum MutationType {
  CREATED
  UPDATED
  DELETED
}

interface Node {
  id: ID!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Query {
  balance(where: BalanceWhereUniqueInput!): Balance
  balances(where: BalanceWhereInput, orderBy: BalanceOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Balance]!
  balancesConnection(where: BalanceWhereInput, orderBy: BalanceOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): BalanceConnection!
  finance(where: FinanceWhereUniqueInput!): Finance
  finances(where: FinanceWhereInput, orderBy: FinanceOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Finance]!
  financesConnection(where: FinanceWhereInput, orderBy: FinanceOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): FinanceConnection!
  queryOrder(where: QueryOrderWhereUniqueInput!): QueryOrder
  queryOrders(where: QueryOrderWhereInput, orderBy: QueryOrderOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [QueryOrder]!
  queryOrdersConnection(where: QueryOrderWhereInput, orderBy: QueryOrderOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): QueryOrderConnection!
  user(where: UserWhereUniqueInput!): User
  users(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [User]!
  usersConnection(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): UserConnection!
  webAddBalance(where: WebAddBalanceWhereUniqueInput!): WebAddBalance
  webAddBalances(where: WebAddBalanceWhereInput, orderBy: WebAddBalanceOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [WebAddBalance]!
  webAddBalancesConnection(where: WebAddBalanceWhereInput, orderBy: WebAddBalanceOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): WebAddBalanceConnection!
  webAmountDiscount(where: WebAmountDiscountWhereUniqueInput!): WebAmountDiscount
  webAmountDiscounts(where: WebAmountDiscountWhereInput, orderBy: WebAmountDiscountOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [WebAmountDiscount]!
  webAmountDiscountsConnection(where: WebAmountDiscountWhereInput, orderBy: WebAmountDiscountOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): WebAmountDiscountConnection!
  node(id: ID!): Node
}

type QueryOrder {
  id: ID!
  Amount: String
  CreateTime: DateTime
  DoneTime: DateTime
  Phone: String
  Product: String
  SerialNumber: String
  State: String
}

type QueryOrderConnection {
  pageInfo: PageInfo!
  edges: [QueryOrderEdge]!
  aggregate: AggregateQueryOrder!
}

input QueryOrderCreateInput {
  id: ID
  Amount: String
  CreateTime: DateTime
  DoneTime: DateTime
  Phone: String
  Product: String
  SerialNumber: String
  State: String
}

type QueryOrderEdge {
  node: QueryOrder!
  cursor: String!
}

enum QueryOrderOrderByInput {
  id_ASC
  id_DESC
  Amount_ASC
  Amount_DESC
  CreateTime_ASC
  CreateTime_DESC
  DoneTime_ASC
  DoneTime_DESC
  Phone_ASC
  Phone_DESC
  Product_ASC
  Product_DESC
  SerialNumber_ASC
  SerialNumber_DESC
  State_ASC
  State_DESC
}

type QueryOrderPreviousValues {
  id: ID!
  Amount: String
  CreateTime: DateTime
  DoneTime: DateTime
  Phone: String
  Product: String
  SerialNumber: String
  State: String
}

type QueryOrderSubscriptionPayload {
  mutation: MutationType!
  node: QueryOrder
  updatedFields: [String!]
  previousValues: QueryOrderPreviousValues
}

input QueryOrderSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: QueryOrderWhereInput
  AND: [QueryOrderSubscriptionWhereInput!]
  OR: [QueryOrderSubscriptionWhereInput!]
  NOT: [QueryOrderSubscriptionWhereInput!]
}

input QueryOrderUpdateInput {
  Amount: String
  CreateTime: DateTime
  DoneTime: DateTime
  Phone: String
  Product: String
  SerialNumber: String
  State: String
}

input QueryOrderUpdateManyMutationInput {
  Amount: String
  CreateTime: DateTime
  DoneTime: DateTime
  Phone: String
  Product: String
  SerialNumber: String
  State: String
}

input QueryOrderWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  Amount: String
  Amount_not: String
  Amount_in: [String!]
  Amount_not_in: [String!]
  Amount_lt: String
  Amount_lte: String
  Amount_gt: String
  Amount_gte: String
  Amount_contains: String
  Amount_not_contains: String
  Amount_starts_with: String
  Amount_not_starts_with: String
  Amount_ends_with: String
  Amount_not_ends_with: String
  CreateTime: DateTime
  CreateTime_not: DateTime
  CreateTime_in: [DateTime!]
  CreateTime_not_in: [DateTime!]
  CreateTime_lt: DateTime
  CreateTime_lte: DateTime
  CreateTime_gt: DateTime
  CreateTime_gte: DateTime
  DoneTime: DateTime
  DoneTime_not: DateTime
  DoneTime_in: [DateTime!]
  DoneTime_not_in: [DateTime!]
  DoneTime_lt: DateTime
  DoneTime_lte: DateTime
  DoneTime_gt: DateTime
  DoneTime_gte: DateTime
  Phone: String
  Phone_not: String
  Phone_in: [String!]
  Phone_not_in: [String!]
  Phone_lt: String
  Phone_lte: String
  Phone_gt: String
  Phone_gte: String
  Phone_contains: String
  Phone_not_contains: String
  Phone_starts_with: String
  Phone_not_starts_with: String
  Phone_ends_with: String
  Phone_not_ends_with: String
  Product: String
  Product_not: String
  Product_in: [String!]
  Product_not_in: [String!]
  Product_lt: String
  Product_lte: String
  Product_gt: String
  Product_gte: String
  Product_contains: String
  Product_not_contains: String
  Product_starts_with: String
  Product_not_starts_with: String
  Product_ends_with: String
  Product_not_ends_with: String
  SerialNumber: String
  SerialNumber_not: String
  SerialNumber_in: [String!]
  SerialNumber_not_in: [String!]
  SerialNumber_lt: String
  SerialNumber_lte: String
  SerialNumber_gt: String
  SerialNumber_gte: String
  SerialNumber_contains: String
  SerialNumber_not_contains: String
  SerialNumber_starts_with: String
  SerialNumber_not_starts_with: String
  SerialNumber_ends_with: String
  SerialNumber_not_ends_with: String
  State: String
  State_not: String
  State_in: [String!]
  State_not_in: [String!]
  State_lt: String
  State_lte: String
  State_gt: String
  State_gte: String
  State_contains: String
  State_not_contains: String
  State_starts_with: String
  State_not_starts_with: String
  State_ends_with: String
  State_not_ends_with: String
  AND: [QueryOrderWhereInput!]
  OR: [QueryOrderWhereInput!]
  NOT: [QueryOrderWhereInput!]
}

input QueryOrderWhereUniqueInput {
  id: ID
}

type Subscription {
  balance(where: BalanceSubscriptionWhereInput): BalanceSubscriptionPayload
  finance(where: FinanceSubscriptionWhereInput): FinanceSubscriptionPayload
  queryOrder(where: QueryOrderSubscriptionWhereInput): QueryOrderSubscriptionPayload
  user(where: UserSubscriptionWhereInput): UserSubscriptionPayload
  webAddBalance(where: WebAddBalanceSubscriptionWhereInput): WebAddBalanceSubscriptionPayload
  webAmountDiscount(where: WebAmountDiscountSubscriptionWhereInput): WebAmountDiscountSubscriptionPayload
}

type User {
  id: ID!
  username: String!
  password: String!
  realname: String!
  createdAt: DateTime!
}

type UserConnection {
  pageInfo: PageInfo!
  edges: [UserEdge]!
  aggregate: AggregateUser!
}

input UserCreateInput {
  id: ID
  username: String!
  password: String!
  realname: String!
}

input UserCreateOneInput {
  create: UserCreateInput
  connect: UserWhereUniqueInput
}

type UserEdge {
  node: User!
  cursor: String!
}

enum UserOrderByInput {
  id_ASC
  id_DESC
  username_ASC
  username_DESC
  password_ASC
  password_DESC
  realname_ASC
  realname_DESC
  createdAt_ASC
  createdAt_DESC
}

type UserPreviousValues {
  id: ID!
  username: String!
  password: String!
  realname: String!
  createdAt: DateTime!
}

type UserSubscriptionPayload {
  mutation: MutationType!
  node: User
  updatedFields: [String!]
  previousValues: UserPreviousValues
}

input UserSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: UserWhereInput
  AND: [UserSubscriptionWhereInput!]
  OR: [UserSubscriptionWhereInput!]
  NOT: [UserSubscriptionWhereInput!]
}

input UserUpdateDataInput {
  username: String
  password: String
  realname: String
}

input UserUpdateInput {
  username: String
  password: String
  realname: String
}

input UserUpdateManyMutationInput {
  username: String
  password: String
  realname: String
}

input UserUpdateOneRequiredInput {
  create: UserCreateInput
  update: UserUpdateDataInput
  upsert: UserUpsertNestedInput
  connect: UserWhereUniqueInput
}

input UserUpsertNestedInput {
  update: UserUpdateDataInput!
  create: UserCreateInput!
}

input UserWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  username: String
  username_not: String
  username_in: [String!]
  username_not_in: [String!]
  username_lt: String
  username_lte: String
  username_gt: String
  username_gte: String
  username_contains: String
  username_not_contains: String
  username_starts_with: String
  username_not_starts_with: String
  username_ends_with: String
  username_not_ends_with: String
  password: String
  password_not: String
  password_in: [String!]
  password_not_in: [String!]
  password_lt: String
  password_lte: String
  password_gt: String
  password_gte: String
  password_contains: String
  password_not_contains: String
  password_starts_with: String
  password_not_starts_with: String
  password_ends_with: String
  password_not_ends_with: String
  realname: String
  realname_not: String
  realname_in: [String!]
  realname_not_in: [String!]
  realname_lt: String
  realname_lte: String
  realname_gt: String
  realname_gte: String
  realname_contains: String
  realname_not_contains: String
  realname_starts_with: String
  realname_not_starts_with: String
  realname_ends_with: String
  realname_not_ends_with: String
  createdAt: DateTime
  createdAt_not: DateTime
  createdAt_in: [DateTime!]
  createdAt_not_in: [DateTime!]
  createdAt_lt: DateTime
  createdAt_lte: DateTime
  createdAt_gt: DateTime
  createdAt_gte: DateTime
  AND: [UserWhereInput!]
  OR: [UserWhereInput!]
  NOT: [UserWhereInput!]
}

input UserWhereUniqueInput {
  id: ID
  username: String
}

type WebAddBalance {
  id: ID!
  Amount: String
  Createtime: DateTime
  User: User!
}

type WebAddBalanceConnection {
  pageInfo: PageInfo!
  edges: [WebAddBalanceEdge]!
  aggregate: AggregateWebAddBalance!
}

input WebAddBalanceCreateInput {
  id: ID
  Amount: String
  Createtime: DateTime
  User: UserCreateOneInput!
}

type WebAddBalanceEdge {
  node: WebAddBalance!
  cursor: String!
}

enum WebAddBalanceOrderByInput {
  id_ASC
  id_DESC
  Amount_ASC
  Amount_DESC
  Createtime_ASC
  Createtime_DESC
}

type WebAddBalancePreviousValues {
  id: ID!
  Amount: String
  Createtime: DateTime
}

type WebAddBalanceSubscriptionPayload {
  mutation: MutationType!
  node: WebAddBalance
  updatedFields: [String!]
  previousValues: WebAddBalancePreviousValues
}

input WebAddBalanceSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: WebAddBalanceWhereInput
  AND: [WebAddBalanceSubscriptionWhereInput!]
  OR: [WebAddBalanceSubscriptionWhereInput!]
  NOT: [WebAddBalanceSubscriptionWhereInput!]
}

input WebAddBalanceUpdateInput {
  Amount: String
  Createtime: DateTime
  User: UserUpdateOneRequiredInput
}

input WebAddBalanceUpdateManyMutationInput {
  Amount: String
  Createtime: DateTime
}

input WebAddBalanceWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  Amount: String
  Amount_not: String
  Amount_in: [String!]
  Amount_not_in: [String!]
  Amount_lt: String
  Amount_lte: String
  Amount_gt: String
  Amount_gte: String
  Amount_contains: String
  Amount_not_contains: String
  Amount_starts_with: String
  Amount_not_starts_with: String
  Amount_ends_with: String
  Amount_not_ends_with: String
  Createtime: DateTime
  Createtime_not: DateTime
  Createtime_in: [DateTime!]
  Createtime_not_in: [DateTime!]
  Createtime_lt: DateTime
  Createtime_lte: DateTime
  Createtime_gt: DateTime
  Createtime_gte: DateTime
  User: UserWhereInput
  AND: [WebAddBalanceWhereInput!]
  OR: [WebAddBalanceWhereInput!]
  NOT: [WebAddBalanceWhereInput!]
}

input WebAddBalanceWhereUniqueInput {
  id: ID
}

type WebAmountDiscount {
  id: ID!
  DiscountCM10: String
  DiscountCM100: String
  DiscountCM20: String
  DiscountCM200: String
  DiscountCM30: String
  DiscountCM300: String
  DiscountCM50: String
  DiscountCM500: String
  DiscountCT10: String
  DiscountCT100: String
  DiscountCT20: String
  DiscountCT200: String
  DiscountCT30: String
  DiscountCT300: String
  DiscountCT50: String
  DiscountCT500: String
  DiscountCU10: String
  DiscountCU100: String
  DiscountCU20: String
  DiscountCU200: String
  DiscountCU30: String
  DiscountCU300: String
  DiscountCU50: String
  DiscountCU500: String
}

type WebAmountDiscountConnection {
  pageInfo: PageInfo!
  edges: [WebAmountDiscountEdge]!
  aggregate: AggregateWebAmountDiscount!
}

input WebAmountDiscountCreateInput {
  id: ID
  DiscountCM10: String
  DiscountCM100: String
  DiscountCM20: String
  DiscountCM200: String
  DiscountCM30: String
  DiscountCM300: String
  DiscountCM50: String
  DiscountCM500: String
  DiscountCT10: String
  DiscountCT100: String
  DiscountCT20: String
  DiscountCT200: String
  DiscountCT30: String
  DiscountCT300: String
  DiscountCT50: String
  DiscountCT500: String
  DiscountCU10: String
  DiscountCU100: String
  DiscountCU20: String
  DiscountCU200: String
  DiscountCU30: String
  DiscountCU300: String
  DiscountCU50: String
  DiscountCU500: String
}

type WebAmountDiscountEdge {
  node: WebAmountDiscount!
  cursor: String!
}

enum WebAmountDiscountOrderByInput {
  id_ASC
  id_DESC
  DiscountCM10_ASC
  DiscountCM10_DESC
  DiscountCM100_ASC
  DiscountCM100_DESC
  DiscountCM20_ASC
  DiscountCM20_DESC
  DiscountCM200_ASC
  DiscountCM200_DESC
  DiscountCM30_ASC
  DiscountCM30_DESC
  DiscountCM300_ASC
  DiscountCM300_DESC
  DiscountCM50_ASC
  DiscountCM50_DESC
  DiscountCM500_ASC
  DiscountCM500_DESC
  DiscountCT10_ASC
  DiscountCT10_DESC
  DiscountCT100_ASC
  DiscountCT100_DESC
  DiscountCT20_ASC
  DiscountCT20_DESC
  DiscountCT200_ASC
  DiscountCT200_DESC
  DiscountCT30_ASC
  DiscountCT30_DESC
  DiscountCT300_ASC
  DiscountCT300_DESC
  DiscountCT50_ASC
  DiscountCT50_DESC
  DiscountCT500_ASC
  DiscountCT500_DESC
  DiscountCU10_ASC
  DiscountCU10_DESC
  DiscountCU100_ASC
  DiscountCU100_DESC
  DiscountCU20_ASC
  DiscountCU20_DESC
  DiscountCU200_ASC
  DiscountCU200_DESC
  DiscountCU30_ASC
  DiscountCU30_DESC
  DiscountCU300_ASC
  DiscountCU300_DESC
  DiscountCU50_ASC
  DiscountCU50_DESC
  DiscountCU500_ASC
  DiscountCU500_DESC
}

type WebAmountDiscountPreviousValues {
  id: ID!
  DiscountCM10: String
  DiscountCM100: String
  DiscountCM20: String
  DiscountCM200: String
  DiscountCM30: String
  DiscountCM300: String
  DiscountCM50: String
  DiscountCM500: String
  DiscountCT10: String
  DiscountCT100: String
  DiscountCT20: String
  DiscountCT200: String
  DiscountCT30: String
  DiscountCT300: String
  DiscountCT50: String
  DiscountCT500: String
  DiscountCU10: String
  DiscountCU100: String
  DiscountCU20: String
  DiscountCU200: String
  DiscountCU30: String
  DiscountCU300: String
  DiscountCU50: String
  DiscountCU500: String
}

type WebAmountDiscountSubscriptionPayload {
  mutation: MutationType!
  node: WebAmountDiscount
  updatedFields: [String!]
  previousValues: WebAmountDiscountPreviousValues
}

input WebAmountDiscountSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: WebAmountDiscountWhereInput
  AND: [WebAmountDiscountSubscriptionWhereInput!]
  OR: [WebAmountDiscountSubscriptionWhereInput!]
  NOT: [WebAmountDiscountSubscriptionWhereInput!]
}

input WebAmountDiscountUpdateInput {
  DiscountCM10: String
  DiscountCM100: String
  DiscountCM20: String
  DiscountCM200: String
  DiscountCM30: String
  DiscountCM300: String
  DiscountCM50: String
  DiscountCM500: String
  DiscountCT10: String
  DiscountCT100: String
  DiscountCT20: String
  DiscountCT200: String
  DiscountCT30: String
  DiscountCT300: String
  DiscountCT50: String
  DiscountCT500: String
  DiscountCU10: String
  DiscountCU100: String
  DiscountCU20: String
  DiscountCU200: String
  DiscountCU30: String
  DiscountCU300: String
  DiscountCU50: String
  DiscountCU500: String
}

input WebAmountDiscountUpdateManyMutationInput {
  DiscountCM10: String
  DiscountCM100: String
  DiscountCM20: String
  DiscountCM200: String
  DiscountCM30: String
  DiscountCM300: String
  DiscountCM50: String
  DiscountCM500: String
  DiscountCT10: String
  DiscountCT100: String
  DiscountCT20: String
  DiscountCT200: String
  DiscountCT30: String
  DiscountCT300: String
  DiscountCT50: String
  DiscountCT500: String
  DiscountCU10: String
  DiscountCU100: String
  DiscountCU20: String
  DiscountCU200: String
  DiscountCU30: String
  DiscountCU300: String
  DiscountCU50: String
  DiscountCU500: String
}

input WebAmountDiscountWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  DiscountCM10: String
  DiscountCM10_not: String
  DiscountCM10_in: [String!]
  DiscountCM10_not_in: [String!]
  DiscountCM10_lt: String
  DiscountCM10_lte: String
  DiscountCM10_gt: String
  DiscountCM10_gte: String
  DiscountCM10_contains: String
  DiscountCM10_not_contains: String
  DiscountCM10_starts_with: String
  DiscountCM10_not_starts_with: String
  DiscountCM10_ends_with: String
  DiscountCM10_not_ends_with: String
  DiscountCM100: String
  DiscountCM100_not: String
  DiscountCM100_in: [String!]
  DiscountCM100_not_in: [String!]
  DiscountCM100_lt: String
  DiscountCM100_lte: String
  DiscountCM100_gt: String
  DiscountCM100_gte: String
  DiscountCM100_contains: String
  DiscountCM100_not_contains: String
  DiscountCM100_starts_with: String
  DiscountCM100_not_starts_with: String
  DiscountCM100_ends_with: String
  DiscountCM100_not_ends_with: String
  DiscountCM20: String
  DiscountCM20_not: String
  DiscountCM20_in: [String!]
  DiscountCM20_not_in: [String!]
  DiscountCM20_lt: String
  DiscountCM20_lte: String
  DiscountCM20_gt: String
  DiscountCM20_gte: String
  DiscountCM20_contains: String
  DiscountCM20_not_contains: String
  DiscountCM20_starts_with: String
  DiscountCM20_not_starts_with: String
  DiscountCM20_ends_with: String
  DiscountCM20_not_ends_with: String
  DiscountCM200: String
  DiscountCM200_not: String
  DiscountCM200_in: [String!]
  DiscountCM200_not_in: [String!]
  DiscountCM200_lt: String
  DiscountCM200_lte: String
  DiscountCM200_gt: String
  DiscountCM200_gte: String
  DiscountCM200_contains: String
  DiscountCM200_not_contains: String
  DiscountCM200_starts_with: String
  DiscountCM200_not_starts_with: String
  DiscountCM200_ends_with: String
  DiscountCM200_not_ends_with: String
  DiscountCM30: String
  DiscountCM30_not: String
  DiscountCM30_in: [String!]
  DiscountCM30_not_in: [String!]
  DiscountCM30_lt: String
  DiscountCM30_lte: String
  DiscountCM30_gt: String
  DiscountCM30_gte: String
  DiscountCM30_contains: String
  DiscountCM30_not_contains: String
  DiscountCM30_starts_with: String
  DiscountCM30_not_starts_with: String
  DiscountCM30_ends_with: String
  DiscountCM30_not_ends_with: String
  DiscountCM300: String
  DiscountCM300_not: String
  DiscountCM300_in: [String!]
  DiscountCM300_not_in: [String!]
  DiscountCM300_lt: String
  DiscountCM300_lte: String
  DiscountCM300_gt: String
  DiscountCM300_gte: String
  DiscountCM300_contains: String
  DiscountCM300_not_contains: String
  DiscountCM300_starts_with: String
  DiscountCM300_not_starts_with: String
  DiscountCM300_ends_with: String
  DiscountCM300_not_ends_with: String
  DiscountCM50: String
  DiscountCM50_not: String
  DiscountCM50_in: [String!]
  DiscountCM50_not_in: [String!]
  DiscountCM50_lt: String
  DiscountCM50_lte: String
  DiscountCM50_gt: String
  DiscountCM50_gte: String
  DiscountCM50_contains: String
  DiscountCM50_not_contains: String
  DiscountCM50_starts_with: String
  DiscountCM50_not_starts_with: String
  DiscountCM50_ends_with: String
  DiscountCM50_not_ends_with: String
  DiscountCM500: String
  DiscountCM500_not: String
  DiscountCM500_in: [String!]
  DiscountCM500_not_in: [String!]
  DiscountCM500_lt: String
  DiscountCM500_lte: String
  DiscountCM500_gt: String
  DiscountCM500_gte: String
  DiscountCM500_contains: String
  DiscountCM500_not_contains: String
  DiscountCM500_starts_with: String
  DiscountCM500_not_starts_with: String
  DiscountCM500_ends_with: String
  DiscountCM500_not_ends_with: String
  DiscountCT10: String
  DiscountCT10_not: String
  DiscountCT10_in: [String!]
  DiscountCT10_not_in: [String!]
  DiscountCT10_lt: String
  DiscountCT10_lte: String
  DiscountCT10_gt: String
  DiscountCT10_gte: String
  DiscountCT10_contains: String
  DiscountCT10_not_contains: String
  DiscountCT10_starts_with: String
  DiscountCT10_not_starts_with: String
  DiscountCT10_ends_with: String
  DiscountCT10_not_ends_with: String
  DiscountCT100: String
  DiscountCT100_not: String
  DiscountCT100_in: [String!]
  DiscountCT100_not_in: [String!]
  DiscountCT100_lt: String
  DiscountCT100_lte: String
  DiscountCT100_gt: String
  DiscountCT100_gte: String
  DiscountCT100_contains: String
  DiscountCT100_not_contains: String
  DiscountCT100_starts_with: String
  DiscountCT100_not_starts_with: String
  DiscountCT100_ends_with: String
  DiscountCT100_not_ends_with: String
  DiscountCT20: String
  DiscountCT20_not: String
  DiscountCT20_in: [String!]
  DiscountCT20_not_in: [String!]
  DiscountCT20_lt: String
  DiscountCT20_lte: String
  DiscountCT20_gt: String
  DiscountCT20_gte: String
  DiscountCT20_contains: String
  DiscountCT20_not_contains: String
  DiscountCT20_starts_with: String
  DiscountCT20_not_starts_with: String
  DiscountCT20_ends_with: String
  DiscountCT20_not_ends_with: String
  DiscountCT200: String
  DiscountCT200_not: String
  DiscountCT200_in: [String!]
  DiscountCT200_not_in: [String!]
  DiscountCT200_lt: String
  DiscountCT200_lte: String
  DiscountCT200_gt: String
  DiscountCT200_gte: String
  DiscountCT200_contains: String
  DiscountCT200_not_contains: String
  DiscountCT200_starts_with: String
  DiscountCT200_not_starts_with: String
  DiscountCT200_ends_with: String
  DiscountCT200_not_ends_with: String
  DiscountCT30: String
  DiscountCT30_not: String
  DiscountCT30_in: [String!]
  DiscountCT30_not_in: [String!]
  DiscountCT30_lt: String
  DiscountCT30_lte: String
  DiscountCT30_gt: String
  DiscountCT30_gte: String
  DiscountCT30_contains: String
  DiscountCT30_not_contains: String
  DiscountCT30_starts_with: String
  DiscountCT30_not_starts_with: String
  DiscountCT30_ends_with: String
  DiscountCT30_not_ends_with: String
  DiscountCT300: String
  DiscountCT300_not: String
  DiscountCT300_in: [String!]
  DiscountCT300_not_in: [String!]
  DiscountCT300_lt: String
  DiscountCT300_lte: String
  DiscountCT300_gt: String
  DiscountCT300_gte: String
  DiscountCT300_contains: String
  DiscountCT300_not_contains: String
  DiscountCT300_starts_with: String
  DiscountCT300_not_starts_with: String
  DiscountCT300_ends_with: String
  DiscountCT300_not_ends_with: String
  DiscountCT50: String
  DiscountCT50_not: String
  DiscountCT50_in: [String!]
  DiscountCT50_not_in: [String!]
  DiscountCT50_lt: String
  DiscountCT50_lte: String
  DiscountCT50_gt: String
  DiscountCT50_gte: String
  DiscountCT50_contains: String
  DiscountCT50_not_contains: String
  DiscountCT50_starts_with: String
  DiscountCT50_not_starts_with: String
  DiscountCT50_ends_with: String
  DiscountCT50_not_ends_with: String
  DiscountCT500: String
  DiscountCT500_not: String
  DiscountCT500_in: [String!]
  DiscountCT500_not_in: [String!]
  DiscountCT500_lt: String
  DiscountCT500_lte: String
  DiscountCT500_gt: String
  DiscountCT500_gte: String
  DiscountCT500_contains: String
  DiscountCT500_not_contains: String
  DiscountCT500_starts_with: String
  DiscountCT500_not_starts_with: String
  DiscountCT500_ends_with: String
  DiscountCT500_not_ends_with: String
  DiscountCU10: String
  DiscountCU10_not: String
  DiscountCU10_in: [String!]
  DiscountCU10_not_in: [String!]
  DiscountCU10_lt: String
  DiscountCU10_lte: String
  DiscountCU10_gt: String
  DiscountCU10_gte: String
  DiscountCU10_contains: String
  DiscountCU10_not_contains: String
  DiscountCU10_starts_with: String
  DiscountCU10_not_starts_with: String
  DiscountCU10_ends_with: String
  DiscountCU10_not_ends_with: String
  DiscountCU100: String
  DiscountCU100_not: String
  DiscountCU100_in: [String!]
  DiscountCU100_not_in: [String!]
  DiscountCU100_lt: String
  DiscountCU100_lte: String
  DiscountCU100_gt: String
  DiscountCU100_gte: String
  DiscountCU100_contains: String
  DiscountCU100_not_contains: String
  DiscountCU100_starts_with: String
  DiscountCU100_not_starts_with: String
  DiscountCU100_ends_with: String
  DiscountCU100_not_ends_with: String
  DiscountCU20: String
  DiscountCU20_not: String
  DiscountCU20_in: [String!]
  DiscountCU20_not_in: [String!]
  DiscountCU20_lt: String
  DiscountCU20_lte: String
  DiscountCU20_gt: String
  DiscountCU20_gte: String
  DiscountCU20_contains: String
  DiscountCU20_not_contains: String
  DiscountCU20_starts_with: String
  DiscountCU20_not_starts_with: String
  DiscountCU20_ends_with: String
  DiscountCU20_not_ends_with: String
  DiscountCU200: String
  DiscountCU200_not: String
  DiscountCU200_in: [String!]
  DiscountCU200_not_in: [String!]
  DiscountCU200_lt: String
  DiscountCU200_lte: String
  DiscountCU200_gt: String
  DiscountCU200_gte: String
  DiscountCU200_contains: String
  DiscountCU200_not_contains: String
  DiscountCU200_starts_with: String
  DiscountCU200_not_starts_with: String
  DiscountCU200_ends_with: String
  DiscountCU200_not_ends_with: String
  DiscountCU30: String
  DiscountCU30_not: String
  DiscountCU30_in: [String!]
  DiscountCU30_not_in: [String!]
  DiscountCU30_lt: String
  DiscountCU30_lte: String
  DiscountCU30_gt: String
  DiscountCU30_gte: String
  DiscountCU30_contains: String
  DiscountCU30_not_contains: String
  DiscountCU30_starts_with: String
  DiscountCU30_not_starts_with: String
  DiscountCU30_ends_with: String
  DiscountCU30_not_ends_with: String
  DiscountCU300: String
  DiscountCU300_not: String
  DiscountCU300_in: [String!]
  DiscountCU300_not_in: [String!]
  DiscountCU300_lt: String
  DiscountCU300_lte: String
  DiscountCU300_gt: String
  DiscountCU300_gte: String
  DiscountCU300_contains: String
  DiscountCU300_not_contains: String
  DiscountCU300_starts_with: String
  DiscountCU300_not_starts_with: String
  DiscountCU300_ends_with: String
  DiscountCU300_not_ends_with: String
  DiscountCU50: String
  DiscountCU50_not: String
  DiscountCU50_in: [String!]
  DiscountCU50_not_in: [String!]
  DiscountCU50_lt: String
  DiscountCU50_lte: String
  DiscountCU50_gt: String
  DiscountCU50_gte: String
  DiscountCU50_contains: String
  DiscountCU50_not_contains: String
  DiscountCU50_starts_with: String
  DiscountCU50_not_starts_with: String
  DiscountCU50_ends_with: String
  DiscountCU50_not_ends_with: String
  DiscountCU500: String
  DiscountCU500_not: String
  DiscountCU500_in: [String!]
  DiscountCU500_not_in: [String!]
  DiscountCU500_lt: String
  DiscountCU500_lte: String
  DiscountCU500_gt: String
  DiscountCU500_gte: String
  DiscountCU500_contains: String
  DiscountCU500_not_contains: String
  DiscountCU500_starts_with: String
  DiscountCU500_not_starts_with: String
  DiscountCU500_ends_with: String
  DiscountCU500_not_ends_with: String
  AND: [WebAmountDiscountWhereInput!]
  OR: [WebAmountDiscountWhereInput!]
  NOT: [WebAmountDiscountWhereInput!]
}

input WebAmountDiscountWhereUniqueInput {
  id: ID
}
`
      }
    